In [2]:
import torch
import random

### 1. Write the Python code to implement a single neuron. - Frak this Im writin C++

In [3]:
class Neuron:
    def __init__(self, activation_function, n_in, n_out):
        self.n_in = n_in
        self.n_out = n_out
        self.out_weights = [random.choice([0.001*i for i in range(-1000, 1000)]) for _ in range(n_out)]
        self.activation_function = activation_function
        self.out = None
    
    def __call__(self, input):
        print(f"length={len(input)}, {input=}")
        print(f"{self.n_in=}")
        if len(input) != self.n_in:
            raise Exception("N inputs does not match definition!")
    
        self.out = self.activation_function(sum(input))

### 2. Write the Python code to implement ReLU.

In [4]:
class ReLU:
    def __init__(self):
        pass
    def __call__(self, input : int):
        if input > 0:
            return input
        else:
            return 0

### 3. Write the Python code for a dense layer in terms of matrix multiplication.

#### As matrix multiplication in math notation

$$
\mathbf{Out} = 
\begin{bmatrix}
out_1 \\
out_2 \\
\vdots \\
out_n
\end{bmatrix}
$$
$$
\mathbf{W} = 
\begin{bmatrix}
w_{11} & w_{12} & \cdots & w_{1m} \\
w_{21} & w_{22} & \cdots & w_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
w_{n1} & w_{n2} & \cdots & w_{nm}
\end{bmatrix}
$$
$$
\mathbf{Z} = \mathbf{Out} \times \mathbf{W}
$$

$$
\mathbf{Z} = 
\begin{bmatrix}
out_1 \\
out_2 \\
\vdots \\
out_n
\end{bmatrix}
\times
\begin{bmatrix}
w_{11} & w_{12} & \cdots & w_{1m} \\
w_{21} & w_{22} & \cdots & w_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
w_{n1} & w_{n2} & \cdots & w_{nm}
\end{bmatrix}
$$

Donde Z será la preactivación de la siguiente capa de la red neuronal

#### In Python

In [5]:
relu_activation = ReLU()

n_in = random.choice([i for i in range(1, 5)])
n_hidden = random.choice([i for i in range(1, 5)])
n_out = random.choice([i for i in range(1, 5)])
layer_1_size = random.choice([i for i in range(1, 5)])
layer_2_size = n_hidden
print("### PARAMETERS ###")
print(f"{layer_1_size=}")
print(f"{layer_2_size=}")
print(f"{n_in=}")
print(f"{n_hidden=}")
print(f"{n_out=}")
print("### END PARAMETERS ###")

layer_1 = [Neuron(activation_function=relu_activation, n_in=n_in, n_out=n_hidden) for _ in range(layer_1_size)]
layer_2 = [Neuron(activation_function=relu_activation, n_in=layer_1_size, n_out=n_out) for _ in range(layer_2_size)]

print(f"Layer 1 neurons!")
for idx, neuron in enumerate(layer_1):
    print(f"Neuron {idx + 1}!")
    random_input = [random.choice([0.001*i for i in range(-1000, 1000)]) for _ in range(n_in)]
    neuron(random_input)

print(f"Layer 2 neurons!")
for idx, neuron_2 in enumerate(layer_2):
    neuron_2_inp = [neuron_1.out_weights[idx] * neuron_1.out for neuron_1 in layer_1]
    neuron_2(neuron_2_inp)

# Es lo mismo que arriba pero visto desde otra perspectiva. A fin de cuentas estamos iterando sobre los pesos de salida de la capa previa y multiplicando por esa activación de salida

### PARAMETERS ###
layer_1_size=4
layer_2_size=1
n_in=2
n_hidden=1
n_out=4
### END PARAMETERS ###
Layer 1 neurons!
Neuron 1!
length=2, input=[-0.795, 0.146]
self.n_in=2
Neuron 2!
length=2, input=[-0.514, 0.422]
self.n_in=2
Neuron 3!
length=2, input=[-0.373, 0.657]
self.n_in=2
Neuron 4!
length=2, input=[0.154, 0.6890000000000001]
self.n_in=2
Layer 2 neurons!
length=4, input=[-0.0, -0.0, -0.09002800000000001, 0.12982200000000002]
self.n_in=4


### 4. Write the Python code for a dense layer in plain Python (that is, with list comprehensions and functionality built into Python).
Did at 3?

### 5. What is the "hidden size" of a layer?
Output of the layer. Normally used before the final layer of the neural net since the last output would be the output size already.

### 6. What does the t method do in PyTorch?
Transpose the matrix/tensor

### 7. Why is matrix multiplication written in plain Python very slow?
Because it uses the native Python implementation which is slow when it comes to for loops. 

### 8. In matmul, why is ac==br. That is: given the matmul AxB, why must A's columns be of the same size as B's rows?
Well that's how they taught me at school :v.
Besides that, We multiply and add the values of the row in the first matrix to each of the values of the column of the other one. If the sizes weren't equal, this operation would not be possible.

**From chatGPT**
When you multiply two matrices, each element of the resulting matrix is a dot product between a row from matrix A and a column from matrix B.  
→ So if c ≠ b, you can’t compute the dot product because the two vectors don’t align in size.

### 9. In Jupyter Notebook, how do you measure the time taken for a single cell to execute?
Using %time

### 10. What is "elementwise arithmetic"?
Applying the same operation to all elements in 2 tensors. To do so, both tensors must be of the same rank and dim size.

### 11. Write the PyTorch code to test whether every element of a is greater than the corresponding element of b.

In [ ]:
a = torch.randn(100, 200)
b = torch.randn(100, 200)

(a > b).all()

tensor(False)

### 12. What is a rank-0 tensor? How do you convert it to a plain Python data type?
It simply is a value like a float. We can convert it to Python simply by casting it like:

In [13]:
rank0 = torch.tensor(1.)
rank0, float(rank0)

(tensor(1.), 1.0)

### 13. What does this return, and why? tensor([1,2]) + tensor([1])

In [31]:
torch.tensor([1,2]) + torch.tensor([1])

tensor([2, 3])

Because since they both have the same rank (1) and one of them has size 1 which makes it broadcastable

### 14. What does this return, and why? tensor([1,2]) + tensor([1,2,3])

In [27]:
torch.tensor([1,2]) + torch.tensor([1, 2, 3])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

Because since they both have the same rank (1) but neither of them has size 1 on said rank, there is no broadcast possible

### 15. How does elementwise arithmetic help us speed up matmul?

Since the dot product (matrix multiplication) can be expressed as elementwise arithmetic by using 2 vectors, it speeds up the matrix multiplication

### 16. What are the broadcasting rules?
1. Each tensor has at least one dimension.
2. To be broadcastable, after aligning the dimensions to the right, tensors' dimensions must be either equal, 1 or non existant from right to left

<!-- ### 17. What is expand_as? Show an example of how it can be used to match the results of broadcasting. -->
Expand this tensor to the same size as other. self.expand_as(other) is equivalent to self.expand(other.size()).

### 18. How does unsqueeze help us to solve certain broadcasting problems?
By adding a size 1 dimension in specific parts thay may need it for broadcasting

### 19. How can we use indexing to do the same operation as unsqueeze?
**De chatGPT** To achieve the same effect as `unsqueeze()` using **indexing**, you can use **`None`** (or `np.newaxis` in NumPy) to add a new dimension. In PyTorch or NumPy, `unsqueeze(dim)` adds a dimension of size 1 at the specified `dim`. Using indexing, you can do the same by inserting `None` in the desired position in the indexing tuple.
```python
import torch

x = torch.tensor([1, 2, 3])  # Shape: [3]

# Using unsqueeze
x_unsq = x.unsqueeze(0)      # Shape: [1, 3]

# Using indexing with None
x_indexed = x[None, :]       # Shape: [1, 3]
```

You can also do:
```python
x.unsqueeze(1)  # Shape: [3, 1]
x[:, None]      # Shape: [3, 1]
```

### 20. How do we show the actual contents of the memory used for a tensor?

In [57]:
x = torch.randn(100,200)
# x.storage()   # Shows memory used in an array (as it would be stored in memory)
x.storage()[2]

0.8089497089385986

### 21. When adding a vector of size 3 to a matrix of size 3×3, are the elements of the vector added to each row or each column of the matrix? (Be sure to check your answer by running this code in a notebook.)

In [66]:
# Each row
vector = torch.randn(3)
vector

tensor([-0.6134, -0.8436,  0.4758])

In [67]:
matrix = torch.randn(3, 3)
matrix

tensor([[-0.6826, -0.5328,  0.0057],
        [ 0.6754, -1.0440, -0.1831],
        [-0.4084, -0.8969,  0.2440]])

In [68]:
vector + matrix

tensor([[-1.2960, -1.3764,  0.4815],
        [ 0.0620, -1.8875,  0.2927],
        [-1.0218, -1.7405,  0.7198]])

#### Even if defined as column vector. For instance

In [ ]:
# Each row
vector = torch.randn(1, 3)
vector

tensor([[0.7786, 0.6067, 1.2278]])

In [70]:
vector + matrix

tensor([[ 0.0961,  0.0739,  1.2335],
        [ 1.4540, -0.4373,  1.0447],
        [ 0.3702, -0.2902,  1.4718]])

### 22. Do broadcasting and expand_as result in increased memory use? Why or why not?
No because we are getting references to already existant data, which makes learning these rules very useful for performance

### 23. Implement matmul using Einstein summation.

In [72]:
x = torch.randn(2, 2)
print(x)
y = torch.randn(2, 3)
print(y)

torch.einsum("ij,jk->ik", x, y)

tensor([[0.5719, 0.7141],
        [0.4804, 1.4062]])
tensor([[ 1.2532, -0.1285, -1.2538],
        [-0.1344, -0.8296,  0.2436]])


tensor([[ 0.6208, -0.6659, -0.5431],
        [ 0.4130, -1.2282, -0.2598]])

### 24. What does a repeated index letter represent on the left-hand side of einsum?
Implicit sum over

### 25. What are the three rules of Einstein summation notation? Why?
1. Repeated indices on the left side are implicitly summed over if they are not on the right side
2. Each index can appear at most twice on the left side
3. Unrepeated indices on the left side must appear on the right side

### 26. What are the forward pass and backward pass of a neural network?
Forward es tira' p'alante y backward es tirah p'atrás
- Forward: Desde el punto de inicio, calcular la salida de cada capa y en consecución calcular las de las subsecuentes capas.
- Backward: Basándonos en una referencia con la que se puede calcular un error, calcular los gradientes desde la última capa hacia la primera que nos servirán para actualizar los parámetros de la red neuronal

### 27. Why do we need to store some of the activations calculated for intermediate layers in the forward pass?
Porque estas se utilizan para el cálculo de los gradientes

### 28. What is the downside of having activations with a standard deviation too far away from 1?
Que en las consecuentes capas de la red neuronal nos encontraremos con activaciones que se incrementarán exponencialmente, destruyendo la fase de propagación

### 29. How can weight initialization help avoid this problem?
Utilizando pesos cuya dimensión mantenga las entradas de cada capa de la red neuronal con un std = 1

### 30. What is the formula to initialize weights such that we get a standard deviation of 1 for a plain linear layer, and for a linear layer followed by ReLU?
Teníamos las inicializaciones de Xavier y de Kaimi:
#### Xavier init
$$
\sqrt\frac{1}{n}\\
$$
#### Kaiming init
$$
\sqrt\frac{2}{n}\\
$$

### 31. Why do we sometimes have to use the squeeze method in loss functions?
Porque una dimensión de tamaño 1 no aporta información alguna. Como podría ser en un vector/tensor columna

### 32. What does the argument to the squeeze method do? Why might it be important to include this argument, even though PyTorch does not require it?
Squeeze to the specific dimension. By default it will be the first to the right. Might include it just to be sure of where is it squeezin

### 33. What is the "chain rule"? Show the equation in either of the two forms presented in this chapter.
Sheeeesh there's plenty of equations in [notes](./Notes.ipynb)

### 34. Show how to calculate the gradients of mse(lin(l2, w2, b2), y) using the chain rule.
Already in [notes](./Notes.ipynb)

### 35. What is the gradient of ReLU? Show it in math or code. (You shouldn't need to commit this to memory—try to figure it using your knowledge of the shape of the function.)
Already in notes too. Altough we might as well say it is 1 when x > 0, else is 0. It's funny cause it's not differentiable at 0 hehe :D

### 36. In what order do we need to call the *_grad functions in the backward pass? Why?
From the furthest layer to the right to the one of the left. That is from the one that outputs, then the previous, then the previous...  
It's like this because we need to compute the gradients based on the gradients of the next layer.

### 37. What is __call__?
Special keyword that allows to call the class in Python

### 38. What methods must we implement when writing a torch.autograd.Function?
Forward and backward methods

### 39. Write nn.Linear from scratch, and test it works.
Done above using Python :v

### 40. What is the difference between nn.Module and fastai's Module?
Basically we do not need to call super()__init__ with fastai Module